name: house-price-mlflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow==2.19.0
      - pandas==2.2.3
      - scikit-learn
      - matplotlib
      - numpy
      - dagshub
