# Triggering the workflow
name: Auto Preprocessing

on:
  push:
    branches:
      - main

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install pandas numpy scikit-learn kaggle

      - name: Configure Kaggle Credentials
        env:
          KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_API_TOKEN }}
        run: |
          mkdir -p ~/.kaggle
          echo $KAGGLE_API_TOKEN > ~/.kaggle/access_token
          chmod 600 ~/.kaggle/access_token

      - name: Run the preprocessing script
        run: |
          cd preprocessing
          python automate_Yana_Suryana.py

      - name: Commit result
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Add the cleaned dataset to the staging area
          git add preprocessing/house-price-dataset_preprocessing.csv
          # Check if there are changes to commit
          if ! git diff --quiet --exit-code; then
            git commit -m "Auto-update cleaned dataset"
            git push
          else
            echo "No changes to commit"
          fi
